@baseUrl = http://localhost:3003

POST {{baseUrl}}/api/blogs
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYWFhIiwiaWQiOiI2YTg4YzQ1MzAxNWUzY2VlMDhhN2VhODciLCJpYXQiOjE3ODczNDgwNjJ9.9lrX1pwpmMBkAD-50VAdSrdI_fFFtbOon0KxsHPcw2I

{
  "title": "bblg",
  "author": "mikki vvvacxssw",
  "url": "url",
  "likes": 99,
  "userId": "6a7d117fefb9283e998b2eea"
}